Repository eos/eos, pull requests merged in 2018-05, with the labels that each got.

#84 [statistics] Fix bugs in hierarchical clustering
  eos/statistics/hierarchical-clustering.cc
Labels: bug

#88 [eos] Implement B->{D^*,rho} form factor parametrizations following [BSZ2015]
  eos/form-factors/mesonic-impl.hh
  eos/form-factors/mesonic.cc
  eos/form-factors/mesonic_TEST.cc
  eos/observable.cc
  eos/parameters/form-factors.yaml
Labels: enhancement, physics

#92 [form-factors] Fix bug at subleading power in HQET results for Lambda_b->Lambda_c^* form factors
  eos/b-decays/lambdab-to-lambdac2595-l-nu_TEST.cc
  eos/b-decays/lambdab-to-lambdac2625-l-nu_TEST.cc
  eos/form-factors/baryonic-impl.hh
  eos/form-factors/baryonic_TEST.cc
Labels: bug, physics

#102 [infra] Fix problems with non-standard Minuit2 installations
  configure.ac
  eos/statistics/Makefile.am
  eos/utils/Makefile.am
  src/clients/Makefile.am
Labels: bug, build

#103 [parameters] Fix the default s-quark mass(2GeV)
  eos/parameters/masses.yaml
Labels: bug
