Repository eos/eos, pull requests merged in 2019-08, with the labels that each got.

#183 [utils] Make scale dependence explicit in wilson_coefficiens_b_to_s
  eos/rare-b-decays/exclusive-b-to-dilepton.cc
  eos/rare-b-decays/exclusive-b-to-s-dilepton-large-recoil.cc
  eos/rare-b-decays/exclusive-b-to-s-dilepton-low-recoil.cc
  eos/rare-b-decays/exclusive-b-to-s-gamma.cc
  eos/rare-b-decays/inclusive-b-to-s-dilepton.cc
  eos/rare-b-decays/inclusive-b-to-s-gamma.cc
  eos/rare-b-decays/lambda-b-to-lambda-dilepton.cc
  eos/utils/model.hh
  eos/utils/standard-model.cc
  eos/utils/standard-model.hh
  eos/utils/standard_model_TEST.cc
  eos/utils/wilson_scan_model.cc
  eos/utils/wilson_scan_model.hh
  eos/utils/wilson_scan_model_TEST.cc
Labels: enhancement, physics

#184 [travis] Switch MacOSX testing image to use XCode 11
  .travis.yml
Labels: bug, build

#185 [statistics] Stop LogLikelihood evaluations early when encountering a…
  eos/statistics/log-likelihood.cc
Labels: enhancement
