Repository eos/eos, pull requests merged in 2019-10, with the labels that each got.

#203 [b-decays] Complete missing new physics contribution to observables
  eos/b-decays/b-to-d-l-nu_TEST.cc
  eos/b-decays/b-to-psd-l-nu.cc
  eos/b-decays/b-to-psd-l-nu.hh
  eos/references.yaml
Labels: enhancement, physics

#205 [b-decays] Fix kinematics descriptions and tidy up SignalPDFs for B->…
  eos/b-decays/b-to-psd-l-nu.cc
  eos/b-decays/b-to-psd-l-nu.hh
  eos/signal-pdf.cc
Labels: doc, enhancement

#208 [eos] Rewriting SignalPDF and companion classes
  eos/b-decays/b-to-d-l-x-nu.cc
  eos/b-decays/b-to-d-l-x-nu.hh
  eos/b-decays/b-to-pi-l-x-nu.cc
  eos/b-decays/b-to-pi-l-x-nu.hh
  eos/b-decays/b-to-psd-l-nu.cc
  eos/b-decays/b-to-psd-l-nu.hh
  eos/signal-pdf.cc
  eos/signal-pdf.hh
  eos/utils/concrete-signal-pdf.hh
Labels: enhancement
