Repository eos/eos, pull requests merged in 2021-12, with the labels that each got.

#437 Use a common parser as parent parser in eos-analysis
  src/scripts/eos-analysis
Labels: bug, command line

#439 [github] Add concurrency in the jobs
  .github/workflows/macos-build+check.yaml
  .github/workflows/manylinux-build+check+deploy.yaml
  .github/workflows/ubuntu-build+check+deploy.yaml
Labels: enhancement

#436 [python] Allow to set scales for the plot axes
  doc/api/python.rst.jinja
  examples/cli/btopilnu.plot
  python/eos/plot/plotter.py
Labels: enhancement

#448 [python] Add the pruning option to the cli and correct bug in the computation of test statistics
  python/eos/data/pypmc.py
  python/eos/tasks.py
  src/scripts/eos-analysis
Labels: bug, command line, python

#449 [python] Add a task to create a cartesian product of mixture densities
  python/eos/data/pypmc.py
  python/eos/tasks.py
  src/scripts/eos-analysis
Labels: enhancement, physics, command line, python
