Repository eos/eos, pull requests merged in 2023-01, with the labels that each got.

#578 [python] Use `numpy.double` instead of the decrepeted `numpy.float` and `numpy.float64`
  python/eos/analysis_TEST.py
  python/eos/plot/plotter.py
Labels: bug, python

#579 [github] Update all workflow actions to their latest version
  .github/workflows/macos-build+check.yaml
  .github/workflows/manylinux-build+check+deploy.yaml
  .github/workflows/ubuntu-build+check+deploy.yaml
Labels: refactoring

#581 Two fixes of eos.Plotter before the refactoring of the entire class
  python/eos/plot/plotter.py
Labels: enhancement, physics

#584 Fix bug in the LaTeX representations of some hadronic parameters
  eos/parameters/hadron-properties.yaml
Labels: bug
