Repository eos/eos, pull requests merged in 2023-06, with the labels that each got.

#638 Implement charm loops as observables
  eos/rare-b-decays/charm-loops-impl.hh
  eos/rare-b-decays/charm-loops.cc
  eos/rare-b-decays/charm-loops.hh
  eos/rare-b-decays/observables.cc
  python/_eos.cc
Labels: enhancement

#643 Split build+deploy step for Ubuntu workflow
  .github/workflows/ubuntu-build+check+deploy.yaml
Labels: bug

#647 [python] Provide the possibiltiy of plotting the graph of a function
  python/eos/plot/plotter.py
Labels: enhancement, physics

#651 [python] Fix the 'end' option in predict_observables
  python/eos/tasks.py
Labels: bug, python
